  version: '3.8'

  services:
  
    mysql:
      image: mysql:latest
      ports:
          - "3306:3306"
      command: --init-file /data/application/init.sql
      volumes:
          - ./init.sql:/data/application/init.sql
      environment:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: s3cr37

    mongo:
      image: mongo:latest
      ports:
        - "27017:27017"
      volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    